### ISSUE TITLE
Dockerfile and container image for CI

### ISSUE THREAD

**Issue by oxr463** [SonarSource/sonarcloud-github-c-cpp#36]
Could we have a `Dockerfile` containing the build wrapper and the sonar-scanner and publish the container image to ghcr.io for use in CI pipelines?

I can submit a PR.

**Comment by oxr463** [comment]
Just found this: https://github.com/SonarSource/sonar-scanner-cli-docker

Unfortunately, doesn't seem to support C projects:
> NB: These Docker images are not compatible with C/C#/C++/Objective-C projects.

**Comment by ericg138** [comment]
Hello @oxr463,
Sorry for not getting back to you sooner.
This is not directly related to this GitHub action, so I will close this issue.
If you still want to pursue this, feel free to open a thread on the [community forum](https://community.sonarsource.com/).
