### ISSUE TITLE
Error while analyzing Pull Request from external contributors

### ISSUE THREAD

**Issue by joelguittet** [SonarSource/sonarcloud-github-c-cpp#46]
Hello @nawar-hamo-sonarsource @anita-stanisz-sonarsource @costin-zaharia-sonarsource @sylvain-combe-sonarsource @lukasz-jarocki-sonarsource 

I just get my first external contribution on a project analyzed by sonarcloud-github-c-cpp but this fails with the following error:

`ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator`

The complete workflow is at https://github.com/joelguittet/mender-mcu-client/actions/runs/6099263242/job/16665602074

I don't understand this error and don't find help. Analysis are properly done on Pull Request initiated internally i.e. if I'm myself branching and creating a PR on my project.

Thanks

Joel

**Comment by sylvain-combe-sonarsource** [comment]
https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request

**Comment by nawar-hamo-sonarsource** [comment]
Hey @joelguittet, 
In case you still have any issues. I would invite you to reach out via our [Community](https://community.sonarsource.com/).

Regards,
Nawar

**Comment by joelguittet** [comment]
Hello, thanks for taking the time to post the answer anyway, next time will go using the community website.
