### ISSUE TITLE
Node 16 deprecation warning

### ISSUE THREAD

**Issue by ajtribick** [SonarSource/sonarcloud-github-c-cpp#49]
This action uses actions/cache@v3, which triggers a Node 16 deprecation warning. Can this be updated to v4?

**Comment by ajtribick** [comment]
Ah, I see there is already a pull request #48

**Comment by 7PH** [comment]
Hey @ajtribick , I'm closing your issue for cleanup as, as you mentioned, there was a merged resolution for it (https://github.com/SonarSource/sonarcloud-github-c-cpp/pull/48)
