### ISSUE TITLE
Possibility of Creating the Release v2.0.3

### ISSUE THREAD

**Issue by Akaame** [SonarSource/sonarcloud-github-c-cpp#56]
https://github.com/SonarSource/sonarcloud-github-c-cpp/pull/48

As it is pointed out here already there have been recent changes to update several things so that this action is not affected by the Node 16 deprecation. Would it be possible to release these changes in a new version? v2.0.3 is just a proposal, I have not checked the changeset since v2.0.2 and do not know if that calls for a major, minor or a patch version change. Pinning to individual commit hashes is not very ideal on our end.

I have created this issue here as there is no discussions enabled for this repository. Please, feel free the close if the issue is out of place.

FYI @claire-villard-sonarsource

**Comment by 7PH** [comment]
Hello @Akaame ,

Thanks for your issue, we indeed need to make a new release for this repository, we will do it once [this PR](https://github.com/SonarSource/sonarcloud-github-c-cpp/pull/57) is merged.

If you have further questions, I would suggest that you create a topic on [our community forum](https://community.sonarsource.com/). We have a process to assign community topics so they can be answered by the relevant team. We are going to remove the issues tab from this repository, so I am closing this issue.

Hope this helps
